title: Aberam's GitHub Portfolio
description: A portfolio to showcase my projects
theme: minima

# Optional settings
author: Aberam Tharmakulenthiran
email: aberamt2002@.com
url: "https://github.com/Aberamt"
baseurl: "/Github-Portfolio"